In [ ]:
import torch
torch.cuda.is_available() # 実行環境でcuda（GPUを利用するためのツール）が使えるかを表示


True

In [ ]:
'''前処理用のモジュールをインポートする'''
import os
import glob
import codecs
import logging
import re
import random
from itertools import chain

'''形態素解析用の外部モジュールをインポートする'''
!pip install janome
from janome.tokenizer import Tokenizer

'''Word2Vec用のモジュールをインポートする'''
from gensim.models import Word2Vec

'''LSTM用のモジュールをインポートする'''
import copy
import numpy as np
from numpy.random import rand # ランダムなベクトルを作るための関数
from tqdm import tqdm # ループの進捗を表示するモジュール
import torch # 深層学習用のモジュールPyTorch
import torch.nn as nn #　ニューラルネットワーク用のモジュール
import torch.nn.functional as F # 活性化関数用のモジュール
import torch.optim as optim # PyTorchのオプティマイザー
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix


     |████████████████████████████████| 19.7MB 1.3MB/s 


In [ ]:
try:
  from google.colab import drive # Google Driveからファイルを読み込むための外部モジュール
  drive.mount('./gdrive')
  # base_dir上に各作者のディレクトリ['natsume', 'dazai', 'akutagawa', 'fukuzawa', 'mori']があることを想定
  base_dir = './gdrive/My Drive/DSAP/DSAP_Presentation/dataset'
# google.colabモジュールが存在しない場合（ローカル環境など）であればbase_dirをスクリプトと同じディレクトリに指定
except ModuleNotFoundError: # Google Colab上で実行しない場合
  base_dir = './'


Mounted at ./gdrive


In [ ]:
RUBY_PATTERN = re.compile(u'《[^》]+》') # ルビの正規表現パターン
ADDITION_PATTERN = re.compile(' ［.*\］| （.*\）') # 文章中の補足情報のパターン（カッコは全角）
ALPHABET_PATTERN = re.compile(u'[a-zA-Z]') # アルファベットの正規表現パターン

def delete_newline_char(line):
  '''改行コードをすべて削除する'''
  return line.replace('\r', '').replace('\n', '')

def remove_ruby(line):
  '''ルビを削除する'''
  return RUBY_PATTERN.sub('', line)

def remove_additions(line):
  '''補足情報を消す'''
  return ADDITION_PATTERN.sub('', line)

def remove_escape_char(line):
  '''エスケープされた文字を消す'''
  return line.replace('\u3000', '')

def remove_symbols(line):
  '''記号を消す'''
  line = line.replace('-', '').replace(':', '').replace('/', '').replace('(', '').replace(')', '')
  return line

def remove_alphabets(line):
  '''アルファベットを消す'''
  return ALPHABET_PATTERN.sub('', line)

def separate_line_with_puncs(lines):
  '''句点で区切った文を吐き出す'''
  for line in lines:
    for sentence in line.split('。'):
      yield sentence

def preprocess(data):
  '''文章を前処理して文のリストにする'''
  lines = map(delete_newline_char, data)
  lines = map(remove_ruby, lines)
  lines = map(remove_additions, lines)
  lines = map(remove_escape_char, lines)
  lines = map(remove_symbols, lines)
  sentences = separate_line_with_puncs(lines)
  '''文が空のものを除去する'''
  sentences = filter(lambda x: len(x), sentences)
  return list(sentences)
  

In [ ]:
WRITERS = ['natsume', 'dazai', 'akutagawa', 'fukuzawa', 'mori'] # 作者のリスト
train_sentences = dict() # 訓練データの辞書（キーは作者の名前、要素は文のリスト）
test_sentences = dict() # テストデータの辞書（キーは作者の名前、要素は文のリスト）
for writer in WRITERS: # ['natsume', 'dazai', 'akutagawa', fukuzawa', 'mori']
  if not os.path.isdir(os.path.join(base_dir, writer)): # 作者名のディレクトリがあるかどうかをチェック
    continue
  train_sentences[writer] = list() # 訓練用の各作者の文を入れるリスト
  test_sentences[writer] = list() # テスト用の各作者の文を入れるリスト
  '''各ディレクトリの全テキストファイルを取得'''
  files = glob.glob(os.path.join(base_dir, writer, '*.txt'))
  '''上で得たテキストファイルを4:1で訓練データとテストデータにする'''
  train_files = files[:len(files) * 4 // 5]
  test_files = files[len(files) * 4 // 5:]

  '''ファイルから文章を読み込み、上で定義したpreprocess関数に通してリストに格納していく'''
  for train_file in train_files:
    with codecs.open(train_file, 'r', 'shift_jis') as f_r:
      train_sentences[writer].extend(preprocess(f_r.readlines()))
  for test_file in test_files:
    with codecs.open(test_file, 'r', 'shift_jis') as f_r:
      test_sentences[writer].extend(preprocess(f_r.readlines()))


In [ ]:
'''各作家の文リストのうち、要素数が一番少ないものの要素数を取得する'''
min_train = min(len(sentences) for sentences in train_sentences.values())
for writer in train_sentences.keys():
  '''上で得た要素数に応じて、他の作者の文を減らす。この時、訓練データをシャッフルする'''
  random.shuffle(train_sentences[writer])
  train_sentences[writer] = train_sentences[writer][:min_train]


In [ ]:
tokenizer = Tokenizer() # 形態素解析用のインスタンスを作成

separated_train_sentences = dict() # 形態素解析した訓練データを格納する辞書
separated_test_sentences = dict() # 形態素解析したテストデータを格納する辞書

for writer in WRITERS:
  separated_train_sentences[writer] = list() # 訓練用の各作者の文を形態素解析したものを入れるリスト
  separated_test_sentences[writer] = list() # テスト用の各作者の文を形態素解析したものを入れるリスト

'''訓練データについて各作者のすべての文について形態素解析を行い、新たに文ごとに形態素のリストを作成する'''
for writer, sentences in train_sentences.items():
  separated_train_sentences[writer] = [[token.surface for token in tokenizer.tokenize(sentence)] for sentence in sentences]

'''テストデータについて各作者のすべての文について形態素解析を行い、新たに文ごとに形態素のリストを作成する'''
for writer, sentences in test_sentences.items():
  separated_test_sentences[writer] = [[token.surface for token in tokenizer.tokenize(sentence)] for sentence in sentences]


In [ ]:
'''Word2Vecのログを表示する際のフォーマットを指定します'''
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)
'''訓練データについてWord2Vecのモデルを作成し学習させます'''
word_model = Word2Vec(chain.from_iterable(separated_train_sentences.values()), size=52, min_count=1, window=5, iter=20)


2021-01-08 02:08:57,435 : INFO : collecting all words and their counts
2021-01-08 02:08:57,436 : INFO : PROGRESS: at sentence #0, processed 0 words, keeping 0 word types
2021-01-08 02:08:57,473 : INFO : collected 15455 word types from a corpus of 179174 raw words and 6735 sentences
2021-01-08 02:08:57,474 : INFO : Loading a fresh vocabulary
2021-01-08 02:08:57,503 : INFO : effective_min_count=1 retains 15455 unique words (100% of original 15455, drops 0)
2021-01-08 02:08:57,506 : INFO : effective_min_count=1 leaves 179174 word corpus (100% of original 179174, drops 0)
2021-01-08 02:08:57,546 : INFO : deleting the raw counts dictionary of 15455 items
2021-01-08 02:08:57,548 : INFO : sample=0.001 downsamples 41 most-common words
2021-01-08 02:08:57,548 : INFO : downsampling leaves estimated 119946 word corpus (66.9% of prior 179174)
2021-01-08 02:08:57,585 : INFO : estimated required memory for 15455 words and 52 dimensions: 14156780 bytes
2021-01-08 02:08:57,586 : INFO : resetting layer

In [ ]:
word_model_path = os.path.join(base_dir, 'word2vec.gensim.model') # 学習済みモデルのパス
'''学習済みモデルをロードする'''
word_model = Word2Vec.load(word_model_path)
'''上記でロードしたモデルについて、自分で用意した訓練データを入れて再学習させる'''
word_model.train(chain.from_iterable(separated_train_sentences.values()), total_examples=sum([len(sentences) for sentences in separated_train_sentences.values()]), epochs=100)


2021-01-08 02:19:51,066 : INFO : loading Word2Vec object from ./gdrive/My Drive/DSAP/DSAP_Presentation/dataset/word2vec.gensim.model
2021-01-08 02:19:52,057 : INFO : loading wv recursively from ./gdrive/My Drive/DSAP/DSAP_Presentation/dataset/word2vec.gensim.model.wv.* with mmap=None
2021-01-08 02:19:52,058 : INFO : loading syn0 from ./gdrive/My Drive/DSAP/DSAP_Presentation/dataset/word2vec.gensim.model.wv.syn0.npy with mmap=None
2021-01-08 02:19:54,559 : INFO : loading syn1neg from ./gdrive/My Drive/DSAP/DSAP_Presentation/dataset/word2vec.gensim.model.syn1neg.npy with mmap=None
2021-01-08 02:19:57,228 : INFO : Model saved using code from earlier Gensim Version. Re-loading old model in a compatible way.
2021-01-08 02:19:57,230 : INFO : loading Word2Vec object from ./gdrive/My Drive/DSAP/DSAP_Presentation/dataset/word2vec.gensim.model
2021-01-08 02:19:58,134 : INFO : loading wv recursively from ./gdrive/My Drive/DSAP/DSAP_Presentation/dataset/word2vec.gensim.model.wv.* with mmap=None
20

(125167, 179174)

In [ ]:
print(word_model.wv['人間'])


[ 0.02454424  0.24313766 -0.11602586  0.1068626  -0.00916309  0.12964547
 -0.57041395  0.37440494 -0.46154094 -0.41853964  0.3872797  -0.03984099
 -0.46275315  0.25286174 -0.20168215  0.3887556   0.21822833 -0.08316327
 -0.33720157  0.01387228  0.79599243  0.39081353 -0.40288326  0.23015828
 -0.13524047 -0.10694273 -0.0375444  -0.00601401  0.45110646  0.03807493
  0.71882373  0.10643985 -0.3844638   0.5986704  -0.61028177  0.1677802
  0.2496373   0.6166424   0.55098814 -0.553066   -0.2972701   0.09899536
  0.36897358  0.23357865  0.9184577  -0.39860702 -0.2824983   1.0004365
 -0.08955841  0.35711867]


In [ ]:
print(word_model.wv.most_similar(['人間']))


2021-01-08 02:20:21,278 : INFO : precomputing L2-norms of word weight vectors


[('本性', 0.8012143969535828), ('自我', 0.8007199764251709), ('もの', 0.7981474995613098), ('他人', 0.7979690432548523), ('肉体', 0.7919148802757263), ('無意識', 0.7917479872703552), ('他者', 0.7867447733879089), ('世の中', 0.7861497402191162), ('心', 0.7839295864105225), ('宿命', 0.7813477516174316)]


In [ ]:
torch.manual_seed(1)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
epoch_num = 100 # 学習を繰り返す回数
batch_size = 100 # バッチサイズ、一度にどれだけの数のデータを一緒に扱って学習するかを決めるパラメータ
lr = 0.001 # 学習率、パラメータを更新する量
embedding_dim = word_model.trainables.layer1_size # 単語の分散表現の次元


In [ ]:
class LSTM(nn.Module):
  '''LSTMを定義するクラス'''

  def __init__(self, embedding_dim, hidden_dim=50): # embedding_dimは入力の次元数

    super(LSTM, self).__init__()
    self.hidden_dim = hidden_dim # 隠れ層の次元
    self.tagset_size = len(WRITERS) # 出力の次元数（作者5人であれば5）

    '''LSTMのモデルを定義する。隠れ層は一層で、biLSTMを使用する'''
    self.lstm = nn.LSTM(embedding_dim, hidden_dim // 2,
                        num_layers=1, bidirectional=True)

    '''全結合層を定義する'''
    self.fc = nn.Linear(hidden_dim * 2, self.tagset_size)

    '''隠れ層を定義する'''
    self.hidden = self._init_hidden()

  def _init_hidden(self): # 隠れ層の初期化を行う関数
    return (torch.randn(2, 1, self.hidden_dim // 2).to(device),
            torch.randn(2, 1, self.hidden_dim // 2).to(device))

  def forward(self, sentence):
    '''入力をLSTMに通す'''
    lstm_out, _ = self.lstm(sentence, self.hidden)
    '''LSTMからの出力を平均プーリングと最大値プーリングに通して結合する'''
    cat_out = torch.cat((torch.max(lstm_out, 0).values, torch.mean(lstm_out, 0)), dim=1)
    '''全結合させる'''
    fc_out = self.fc(cat_out)
    output = F.log_softmax(fc_out, dim=1)
    return output


In [ ]:
def result_log(save_results=False):

  '''正解ラベルの一覧を取得する'''
  y_true = [WRITERS[data[1]] for data in test_data]
  '''推測したラベルの一覧を格納するリストを定義する'''
  y_pred = list()
  '''テストデータで推論を行う際はパラメータの更新を行わないようにする'''
  with torch.no_grad():
    correct_answers = 0
    for sentence, writer_index in test_data:

      '''テストデータの中身をベクトルで置き換える'''
      '''Word2Vecのモデルに存在しない単語が出てきた場合は適当なベクトルで置き換える'''
      sentence_vec = [word_model.wv[word] if word in word_model.wv.vocab
                     else rand(embedding_dim).astype(np.float32) for word in sentence]

      '''すぐ上で用意したベクトルのPyTorchのテンソルに変換する'''
      sentence_in = torch.tensor(sentence_vec).view(len(sentence), 1, -1).to(device)

      '''テストデータについてLSTMに通して推論を行う'''
      output = lstm_model(sentence_in)
      _, pred = torch.max(output, 1)
      y_pred.append(pred)
      target = torch.tensor([writer_index]).to(device)
      if pred == target:
        correct_answers += 1

    print('Test data accuracy: ', correct_answers / len(test_data))
    '''推論結果をNumPyの配列に変換する'''
    y_pred = torch.tensor(y_pred).numpy()
    '''推論結果から作者名を取り出す'''
    y_pred = [WRITERS[pre] for pre in y_pred]
    '''各作者についての詳しいレポートを出力する'''
    report = classification_report(y_true, y_pred)
    '''推論結果と実際のデータに関する混同行列を出力する'''
    cof_mat = confusion_matrix(y_true, y_pred)
    print(report)
    print(cof_mat)
    if save_results:
      with open(os.path.join(base_dir, 'classification_report.txt'), 'w') as f_w:
        f_w.write(report)
      with open(os.path.join(base_dir, 'cof_mat.txt'), 'w') as f_w:
        f_w.write(str(cof_mat))

def save_model(model, epoch=None):
# モデルを保存する関数。10エポックごとと学習終了後に保存
  if epoch:
    path = os.path.join(base_dir, str(epoch) + '-model.pth')
  else:
    path = os.path.join(base_dir, 'model.pth')
  torch.save(model.state_dict(), path)


In [ ]:
train_data = list() # LSTMに入れる訓練データのリスト
test_data = list() # LSTMに入れるテストデータのリスト

'''入力するデータを形態素解析した文とタグのタプルをリストにする'''
for writer, sentences in separated_train_sentences.items():
  writer_index = WRITERS.index(writer)
  for sentence in sentences:
    train_data.append([sentence, writer_index])

'''入力するデータを形態素解析した文とタグのタプルをリストにする'''
for writer, sentences in separated_test_sentences.items():
  writer_index = WRITERS.index(writer)
  for sentence in sentences:
    test_data.append([sentence, writer_index])


In [ ]:
'''LSTMモデルを生成する'''
lstm_model = LSTM(embedding_dim).to(device)

'''optimizerを定義する'''
optimizer = optim.Adam(lstm_model.parameters(), lr=lr)
'''訓練データの個数から1エポック中のループ回数を決定する'''
loop_num = len(train_data) // batch_size


In [ ]:
for epoch in range(epoch_num):
  all_loss = 0
  random.shuffle(train_data) # 毎エポック訓練データの中身をシャッフル
  correct_answers = 0
  print('epoch: ', epoch)
  for i in tqdm(range(0, loop_num)):
    index = i * batch_size
    batch_data = [train_data[j] for j in range(index, index+batch_size)]

    for sentence, writer_index in batch_data:
      lstm_model.zero_grad()

      '''訓練データの中身をベクトルで置き換える'''
      '''Word2Vecモデルに存在しない単語が出てきた場合は適当なベクトルで置き換える'''
      sentence_vec = [word_model.wv[word] if word in word_model.wv.vocab
                     else rand(embedding_dim).astype(np.float32) for word in sentence]

      '''すぐ上で用意したベクトルをPyTorchのテンソルに変換する'''
      sentence_in = torch.tensor(sentence_vec).view(len(sentence), 1, -1).to(device)

      '''同様にラベルの方もPyTorchのテンソルに変換する'''
      target = torch.tensor([writer_index]).to(device)
      output = lstm_model(sentence_in)

      _, pred = torch.max(output, 1)
      if pred == target:
        correct_answers += 1

      loss = F.nll_loss(output, target) # lossを計算
      loss.backward() # 誤差逆伝搬の計算
      optimizer.step() # lossに応じてパラメータを更新
      all_loss += loss.item()

  print('Training data accuracy: ', correct_answers / (loop_num * batch_size))
  print('Loss: ', str(all_loss))

  if epoch % 10 == 0:
    save_model(lstm_model, epoch)
    result_log(save_results=True)
  else:
    result_log()

result_log(save_results=True)
save_model(lstm_model)


  0%|          | 0/67 [00:00<?, ?it/s]

epoch:  0


100%|██████████| 67/67 [00:30<00:00,  2.18it/s]


Training data accuracy:  0.5783582089552238
Loss:  6675.711295971414
Test data accuracy:  0.4668850072780204


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.02      0.11      0.03       261
       dazai       0.36      0.63      0.46      2699
    fukuzawa       0.73      0.78      0.75       634
        mori       0.29      0.22      0.25      3764
     natsume       0.70      0.51      0.59      9130

    accuracy                           0.47     16488
   macro avg       0.42      0.45      0.42     16488
weighted avg       0.54      0.47      0.49     16488

[[  30  136    0   12   83]
 [ 282 1704   20   85  608]
 [   0   77  496   49   12]
 [ 644  994   19  827 1280]
 [ 628 1803  148 1910 4641]]
epoch:  1


100%|██████████| 67/67 [00:31<00:00,  2.14it/s]


Training data accuracy:  0.6877611940298507
Loss:  5234.312661834905
Test data accuracy:  0.4962396894711305


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.11      0.04       261
       dazai       0.51      0.57      0.54      2699
    fukuzawa       0.63      0.90      0.74       634
        mori       0.32      0.45      0.37      3764
     natsume       0.70      0.48      0.57      9130

    accuracy                           0.50     16488
   macro avg       0.44      0.50      0.45     16488
weighted avg       0.57      0.50      0.52     16488

[[  28  124    0   37   72]
 [ 218 1550   34  313  584]
 [   0   10  568   47    9]
 [ 291  528   56 1699 1190]
 [ 451  800  248 3294 4337]]
epoch:  2


100%|██████████| 67/67 [00:30<00:00,  2.17it/s]


Training data accuracy:  0.7185074626865672
Loss:  4672.69762892869
Test data accuracy:  0.4445657447840854


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.05      0.03       261
       dazai       0.36      0.80      0.49      2699
    fukuzawa       0.78      0.62      0.69       634
        mori       0.32      0.45      0.37      3764
     natsume       0.76      0.34      0.47      9130

    accuracy                           0.44     16488
   macro avg       0.45      0.45      0.41     16488
weighted avg       0.58      0.44      0.45     16488

[[  13  177    0   35   36]
 [  82 2171   10  217  219]
 [   0  161  393   64   16]
 [ 121 1237   11 1676  719]
 [ 297 2367   89 3300 3077]]
epoch:  3


100%|██████████| 67/67 [00:31<00:00,  2.16it/s]


Training data accuracy:  0.7559701492537313
Loss:  4231.617435161967
Test data accuracy:  0.5309315866084425


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.02      0.23      0.04       261
       dazai       0.58      0.58      0.58      2699
    fukuzawa       0.66      0.80      0.72       634
        mori       0.41      0.33      0.37      3764
     natsume       0.74      0.59      0.66      9130

    accuracy                           0.53     16488
   macro avg       0.48      0.51      0.47     16488
weighted avg       0.62      0.53      0.57     16488

[[  61  121    0   14   65]
 [ 454 1559   41  140  505]
 [   2   42  510   44   36]
 [ 813  367   45 1243 1296]
 [1384  611  181 1573 5381]]
epoch:  4


100%|██████████| 67/67 [00:31<00:00,  2.16it/s]


Training data accuracy:  0.7750746268656716
Loss:  3889.5454238040875
Test data accuracy:  0.5625303250849102


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.12      0.05       261
       dazai       0.47      0.67      0.55      2699
    fukuzawa       0.68      0.83      0.75       634
        mori       0.42      0.40      0.41      3764
     natsume       0.74      0.59      0.66      9130

    accuracy                           0.56     16488
   macro avg       0.47      0.52      0.48     16488
weighted avg       0.61      0.56      0.58     16488

[[  31  131    0   35   64]
 [ 195 1802   35  186  481]
 [   2   64  526   25   17]
 [ 255  625   38 1523 1323]
 [ 577 1175  170 1815 5393]]
epoch:  5


100%|██████████| 67/67 [00:30<00:00,  2.16it/s]


Training data accuracy:  0.7937313432835821
Loss:  3582.434981748135
Test data accuracy:  0.5217127607957303


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.16      0.05       261
       dazai       0.55      0.66      0.60      2699
    fukuzawa       0.77      0.74      0.75       634
        mori       0.36      0.54      0.43      3764
     natsume       0.76      0.47      0.58      9130

    accuracy                           0.52     16488
   macro avg       0.49      0.51      0.48     16488
weighted avg       0.62      0.52      0.55     16488

[[  42  124    0   43   52]
 [ 225 1790   26  316  342]
 [   1   50  471   85   27]
 [ 427  366   18 2036  917]
 [ 642  926   99 3200 4263]]
epoch:  6


100%|██████████| 67/67 [00:30<00:00,  2.17it/s]


Training data accuracy:  0.8050746268656717
Loss:  3358.7844441152574
Test data accuracy:  0.5825448811256672


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.04      0.13      0.06       261
       dazai       0.63      0.58      0.60      2699
    fukuzawa       0.72      0.80      0.76       634
        mori       0.40      0.47      0.43      3764
     natsume       0.73      0.63      0.67      9130

    accuracy                           0.58     16488
   macro avg       0.50      0.52      0.50     16488
weighted avg       0.62      0.58      0.60     16488

[[  35  109    0   34   83]
 [ 212 1575   30  269  613]
 [   1   27  508   77   21]
 [ 252  277   23 1757 1455]
 [ 452  530  146 2272 5730]]
epoch:  7


100%|██████████| 67/67 [00:31<00:00,  2.16it/s]


Training data accuracy:  0.8238805970149253
Loss:  3120.741693994699
Test data accuracy:  0.5630155264434741


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.04      0.18      0.06       261
       dazai       0.65      0.48      0.55      2699
    fukuzawa       0.78      0.72      0.75       634
        mori       0.39      0.54      0.45      3764
     natsume       0.73      0.60      0.66      9130

    accuracy                           0.56     16488
   macro avg       0.52      0.50      0.49     16488
weighted avg       0.63      0.56      0.59     16488

[[  48   89    0   55   69]
 [ 274 1286   16  412  711]
 [   1   50  456   85   42]
 [ 306  209   15 2041 1193]
 [ 589  357   98 2634 5452]]
epoch:  8


100%|██████████| 67/67 [00:30<00:00,  2.17it/s]


Training data accuracy:  0.8347761194029851
Loss:  2878.761048945711
Test data accuracy:  0.48410965550703544


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.02      0.16      0.04       261
       dazai       0.53      0.68      0.60      2699
    fukuzawa       0.79      0.67      0.73       634
        mori       0.34      0.50      0.40      3764
     natsume       0.73      0.42      0.53      9130

    accuracy                           0.48     16488
   macro avg       0.48      0.49      0.46     16488
weighted avg       0.60      0.48      0.51     16488

[[  42  151    0   26   42]
 [ 229 1840   12  206  412]
 [   2   65  427  132    8]
 [ 496  460   14 1866  928]
 [1056  952   89 3226 3807]]
epoch:  9


100%|██████████| 67/67 [00:30<00:00,  2.17it/s]


Training data accuracy:  0.8465671641791045
Loss:  2721.2988554510175
Test data accuracy:  0.5853954391072295


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.04      0.18      0.06       261
       dazai       0.62      0.52      0.57      2699
    fukuzawa       0.81      0.67      0.73       634
        mori       0.41      0.39      0.40      3764
     natsume       0.71      0.69      0.70      9130

    accuracy                           0.59     16488
   macro avg       0.52      0.49      0.49     16488
weighted avg       0.62      0.59      0.60     16488

[[  46  110    0   22   83]
 [ 266 1413   12  236  772]
 [   1   63  426  109   35]
 [ 305  230   17 1466 1746]
 [ 611  445   73 1700 6301]]
epoch:  10


100%|██████████| 67/67 [00:31<00:00,  2.13it/s]


Training data accuracy:  0.8532835820895522
Loss:  2565.7820479292814
Test data accuracy:  0.48823386705482774


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.16      0.05       261
       dazai       0.42      0.77      0.54      2699
    fukuzawa       0.70      0.76      0.73       634
        mori       0.37      0.46      0.41      3764
     natsume       0.77      0.41      0.53      9130

    accuracy                           0.49     16488
   macro avg       0.46      0.51      0.45     16488
weighted avg       0.61      0.49      0.51     16488

[[  41  158    0   15   47]
 [ 178 2083   26  110  302]
 [   1   57  483   63   30]
 [ 322  982   22 1714  724]
 [ 834 1670  162 2735 3729]]
epoch:  11


100%|██████████| 67/67 [00:31<00:00,  2.16it/s]


Training data accuracy:  0.8656716417910447
Loss:  2403.5827668380502
Test data accuracy:  0.5643498301795244


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.21      0.06       261
       dazai       0.55      0.63      0.59      2699
    fukuzawa       0.76      0.76      0.76       634
        mori       0.44      0.48      0.46      3764
     natsume       0.75      0.58      0.65      9130

    accuracy                           0.56     16488
   macro avg       0.51      0.53      0.50     16488
weighted avg       0.64      0.56      0.59     16488

[[  55  119    0   24   63]
 [ 288 1705   19  238  449]
 [   1   44  484   72   33]
 [ 386  392   18 1798 1170]
 [ 972  817  118 1960 5263]]
epoch:  12


100%|██████████| 67/67 [00:31<00:00,  2.16it/s]


Training data accuracy:  0.876268656716418
Loss:  2230.8582832890024
Test data accuracy:  0.535965550703542


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.17      0.06       261
       dazai       0.47      0.70      0.56      2699
    fukuzawa       0.81      0.65      0.72       634
        mori       0.40      0.45      0.42      3764
     natsume       0.75      0.53      0.62      9130

    accuracy                           0.54     16488
   macro avg       0.49      0.50      0.48     16488
weighted avg       0.61      0.54      0.56     16488

[[  45  132    0   32   52]
 [ 213 1878   13  164  431]
 [   1   89  413   94   37]
 [ 342  602    9 1685 1126]
 [ 752 1254   72 2236 4816]]
epoch:  13


100%|██████████| 67/67 [00:31<00:00,  2.14it/s]


Training data accuracy:  0.8831343283582089
Loss:  2074.9325959102166
Test data accuracy:  0.48799126637554585


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.20      0.05       261
       dazai       0.55      0.62      0.58      2699
    fukuzawa       0.79      0.69      0.74       634
        mori       0.35      0.55      0.43      3764
     natsume       0.75      0.42      0.54      9130

    accuracy                           0.49     16488
   macro avg       0.49      0.50      0.47     16488
weighted avg       0.62      0.49      0.52     16488

[[  52  124    0   43   42]
 [ 297 1675   17  325  385]
 [   2   63  437  112   20]
 [ 529  340   13 2080  802]
 [ 969  863   88 3408 3802]]
epoch:  14


100%|██████████| 67/67 [00:31<00:00,  2.16it/s]


Training data accuracy:  0.8944776119402985
Loss:  1938.4297389499334
Test data accuracy:  0.5219553614750121


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.23      0.06       261
       dazai       0.59      0.58      0.59      2699
    fukuzawa       0.72      0.82      0.77       634
        mori       0.38      0.50      0.43      3764
     natsume       0.74      0.50      0.60      9130

    accuracy                           0.52     16488
   macro avg       0.49      0.53      0.49     16488
weighted avg       0.62      0.52      0.55     16488

[[  61  116    0   33   51]
 [ 312 1574   25  267  521]
 [   3   16  521   56   38]
 [ 545  307   15 1877 1020]
 [ 963  663  167 2764 4573]]
epoch:  15


100%|██████████| 67/67 [00:31<00:00,  2.16it/s]


Training data accuracy:  0.8995522388059701
Loss:  1807.9208960816616
Test data accuracy:  0.5193474041727317


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.05      0.15      0.07       261
       dazai       0.54      0.64      0.58      2699
    fukuzawa       0.79      0.71      0.74       634
        mori       0.36      0.61      0.45      3764
     natsume       0.74      0.44      0.56      9130

    accuracy                           0.52     16488
   macro avg       0.49      0.51      0.48     16488
weighted avg       0.61      0.52      0.54     16488

[[  38  117    0   62   44]
 [ 124 1720   14  367  474]
 [   1   58  447  100   28]
 [ 207  384   10 2304  859]
 [ 460  912   96 3608 4054]]
epoch:  16


100%|██████████| 67/67 [00:31<00:00,  2.14it/s]


Training data accuracy:  0.9095522388059701
Loss:  1654.7139131233344
Test data accuracy:  0.5686559922367783


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.04      0.17      0.06       261
       dazai       0.49      0.67      0.56      2699
    fukuzawa       0.76      0.76      0.76       634
        mori       0.44      0.42      0.43      3764
     natsume       0.74      0.60      0.66      9130

    accuracy                           0.57     16488
   macro avg       0.49      0.52      0.50     16488
weighted avg       0.62      0.57      0.59     16488

[[  44  121    0   21   75]
 [ 210 1795   13  164  517]
 [   1   72  482   47   32]
 [ 310  557   21 1595 1281]
 [ 620 1156  121 1773 5460]]
epoch:  17


100%|██████████| 67/67 [00:31<00:00,  2.15it/s]


Training data accuracy:  0.9134328358208955
Loss:  1581.8396698658762
Test data accuracy:  0.605106744298884


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.12      0.05       261
       dazai       0.56      0.62      0.59      2699
    fukuzawa       0.80      0.63      0.70       634
        mori       0.46      0.43      0.45      3764
     natsume       0.73      0.69      0.71      9130

    accuracy                           0.61     16488
   macro avg       0.52      0.50      0.50     16488
weighted avg       0.63      0.61      0.62     16488

[[  31  127    0   22   81]
 [ 194 1664   11  176  654]
 [   1   90  398   80   65]
 [ 243  391   13 1622 1495]
 [ 469  696   78 1625 6262]]
epoch:  18


100%|██████████| 67/67 [00:31<00:00,  2.14it/s]


Training data accuracy:  0.9176119402985075
Loss:  1460.3851665422544
Test data accuracy:  0.5366327025715673


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.04      0.10      0.06       261
       dazai       0.43      0.75      0.55      2699
    fukuzawa       0.79      0.70      0.74       634
        mori       0.41      0.53      0.47      3764
     natsume       0.77      0.48      0.59      9130

    accuracy                           0.54     16488
   macro avg       0.49      0.51      0.48     16488
weighted avg       0.62      0.54      0.55     16488

[[  27  154    0   40   40]
 [  92 2016    8  229  354]
 [   1   87  443   75   28]
 [ 186  639   13 2012  914]
 [ 401 1761  100 2518 4350]]
epoch:  19


100%|██████████| 67/67 [00:31<00:00,  2.15it/s]


Training data accuracy:  0.9291044776119403
Loss:  1341.9574765232326
Test data accuracy:  0.5192261038330908


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.25      0.05       261
       dazai       0.51      0.65      0.57      2699
    fukuzawa       0.77      0.66      0.71       634
        mori       0.42      0.43      0.42      3764
     natsume       0.76      0.52      0.61      9130

    accuracy                           0.52     16488
   macro avg       0.50      0.50      0.47     16488
weighted avg       0.63      0.52      0.56     16488

[[  64  117    0   20   60]
 [ 346 1760   18  176  399]
 [  10   92  419   82   31]
 [ 683  440   16 1601 1024]
 [1333 1023   90 1967 4717]]
epoch:  20


100%|██████████| 67/67 [00:31<00:00,  2.15it/s]


Training data accuracy:  0.9352238805970149
Loss:  1261.0004777833935
Test data accuracy:  0.5858806404657934


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.04      0.14      0.06       261
       dazai       0.54      0.62      0.58      2699
    fukuzawa       0.67      0.83      0.74       634
        mori       0.44      0.44      0.44      3764
     natsume       0.73      0.63      0.68      9130

    accuracy                           0.59     16488
   macro avg       0.48      0.53      0.50     16488
weighted avg       0.62      0.59      0.60     16488

[[  36  122    0   27   76]
 [ 184 1681   32  201  601]
 [   2   21  524   60   27]
 [ 239  445   21 1671 1388]
 [ 498  870  201 1813 5748]]
epoch:  21


100%|██████████| 67/67 [00:31<00:00,  2.15it/s]


Training data accuracy:  0.9380597014925374
Loss:  1161.6335987685447
Test data accuracy:  0.5721130519165454


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.17      0.05       261
       dazai       0.53      0.63      0.57      2699
    fukuzawa       0.79      0.71      0.74       634
        mori       0.44      0.36      0.39      3764
     natsume       0.72      0.65      0.68      9130

    accuracy                           0.57     16488
   macro avg       0.50      0.50      0.49     16488
weighted avg       0.61      0.57      0.59     16488

[[  45  126    0   15   75]
 [ 185 1699   13  143  659]
 [   6   76  447   61   44]
 [ 413  447   13 1347 1544]
 [ 765  871   96 1503 5895]]
epoch:  22


100%|██████████| 67/67 [00:31<00:00,  2.14it/s]


Training data accuracy:  0.9422388059701493
Loss:  1097.7778850788686
Test data accuracy:  0.5535540999514799


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.19      0.06       261
       dazai       0.54      0.60      0.57      2699
    fukuzawa       0.79      0.64      0.70       634
        mori       0.42      0.44      0.43      3764
     natsume       0.72      0.59      0.65      9130

    accuracy                           0.55     16488
   macro avg       0.50      0.49      0.48     16488
weighted avg       0.61      0.55      0.58     16488

[[  50  115    0   27   69]
 [ 232 1618   12  190  647]
 [   4   74  403  104   49]
 [ 353  382   10 1657 1362]
 [ 819  834   86 1992 5399]]
epoch:  23


100%|██████████| 67/67 [00:31<00:00,  2.13it/s]


Training data accuracy:  0.9491044776119403
Loss:  1017.1516942210743
Test data accuracy:  0.5134036875303251


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.19      0.05       261
       dazai       0.54      0.57      0.55      2699
    fukuzawa       0.77      0.69      0.73       634
        mori       0.38      0.55      0.45      3764
     natsume       0.74      0.48      0.58      9130

    accuracy                           0.51     16488
   macro avg       0.49      0.50      0.47     16488
weighted avg       0.62      0.51      0.54     16488

[[  50  114    0   45   52]
 [ 295 1531   12  368  493]
 [   4   70  436   92   32]
 [ 431  308   14 2072  939]
 [ 946  824  105 2879 4376]]
epoch:  24


100%|██████████| 67/67 [00:30<00:00,  2.16it/s]


Training data accuracy:  0.9528358208955224
Loss:  916.9394951260592
Test data accuracy:  0.5083697234352256


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.13      0.05       261
       dazai       0.47      0.72      0.57      2699
    fukuzawa       0.70      0.80      0.75       634
        mori       0.37      0.56      0.44      3764
     natsume       0.77      0.41      0.54      9130

    accuracy                           0.51     16488
   macro avg       0.47      0.52      0.47     16488
weighted avg       0.61      0.51      0.52     16488

[[  33  142    0   43   43]
 [ 103 1955   28  270  343]
 [   1   34  505   78   16]
 [ 265  617   24 2103  755]
 [ 550 1431  163 3200 3786]]
epoch:  25


100%|██████████| 67/67 [00:31<00:00,  2.16it/s]


Training data accuracy:  0.9547761194029851
Loss:  868.6155250198473
Test data accuracy:  0.5305070354196991


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.13      0.05       261
       dazai       0.42      0.75      0.54      2699
    fukuzawa       0.74      0.66      0.70       634
        mori       0.42      0.44      0.43      3764
     natsume       0.76      0.50      0.61      9130

    accuracy                           0.53     16488
   macro avg       0.47      0.50      0.47     16488
weighted avg       0.62      0.53      0.55     16488

[[  34  147    1   30   49]
 [ 152 2034   12  156  345]
 [   1  104  420   87   22]
 [ 270  807   19 1669  999]
 [ 624 1745  115 2056 4590]]
epoch:  26


100%|██████████| 67/67 [00:31<00:00,  2.14it/s]


Training data accuracy:  0.9583582089552238
Loss:  823.2592914738233
Test data accuracy:  0.5313561377971858


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.12      0.05       261
       dazai       0.50      0.65      0.57      2699
    fukuzawa       0.76      0.68      0.72       634
        mori       0.38      0.53      0.44      3764
     natsume       0.74      0.50      0.60      9130

    accuracy                           0.53     16488
   macro avg       0.48      0.50      0.47     16488
weighted avg       0.61      0.53      0.55     16488

[[  32  117    0   56   56]
 [ 194 1752   13  269  471]
 [   2   76  430  107   19]
 [ 255  483   19 1983 1024]
 [ 600 1062  103 2801 4564]]
epoch:  27


100%|██████████| 67/67 [00:31<00:00,  2.13it/s]


Training data accuracy:  0.9619402985074627
Loss:  765.3325553920247
Test data accuracy:  0.5320839398350315


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.19      0.06       261
       dazai       0.52      0.62      0.56      2699
    fukuzawa       0.78      0.70      0.74       634
        mori       0.39      0.52      0.45      3764
     natsume       0.75      0.51      0.61      9130

    accuracy                           0.53     16488
   macro avg       0.49      0.51      0.48     16488
weighted avg       0.62      0.53      0.56     16488

[[  49  110    0   49   53]
 [ 282 1665   12  257  483]
 [   6   84  442   71   31]
 [ 372  417   13 1955 1007]
 [ 776  952   98 2642 4662]]
epoch:  28


100%|██████████| 67/67 [00:31<00:00,  2.15it/s]


Training data accuracy:  0.9656716417910448
Loss:  667.594789310531
Test data accuracy:  0.5913998059194566


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.04      0.13      0.06       261
       dazai       0.52      0.65      0.58      2699
    fukuzawa       0.70      0.79      0.74       634
        mori       0.44      0.38      0.41      3764
     natsume       0.73      0.66      0.69      9130

    accuracy                           0.59     16488
   macro avg       0.49      0.52      0.50     16488
weighted avg       0.62      0.59      0.60     16488

[[  34  125    1   20   81]
 [ 161 1757   31  172  578]
 [   3   58  499   46   28]
 [ 247  497   27 1418 1575]
 [ 429  961  153 1544 6043]]
epoch:  29


100%|██████████| 67/67 [00:31<00:00,  2.14it/s]


Training data accuracy:  0.968955223880597
Loss:  655.300666825057
Test data accuracy:  0.5374211547792334


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.19      0.05       261
       dazai       0.56      0.57      0.56      2699
    fukuzawa       0.78      0.66      0.71       634
        mori       0.39      0.51      0.44      3764
     natsume       0.75      0.54      0.63      9130

    accuracy                           0.54     16488
   macro avg       0.50      0.49      0.48     16488
weighted avg       0.63      0.54      0.57     16488

[[  50  106    0   47   58]
 [ 321 1542   13  322  501]
 [   4   73  417  108   32]
 [ 473  335   14 1902 1040]
 [ 937  711   91 2441 4950]]
epoch:  30


100%|██████████| 67/67 [00:31<00:00,  2.16it/s]


Training data accuracy:  0.9714925373134329
Loss:  602.0092480268513
Test data accuracy:  0.5415453663270258


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.16      0.06       261
       dazai       0.45      0.70      0.55      2699
    fukuzawa       0.79      0.64      0.71       634
        mori       0.41      0.43      0.42      3764
     natsume       0.75      0.54      0.63      9130

    accuracy                           0.54     16488
   macro avg       0.49      0.50      0.47     16488
weighted avg       0.62      0.54      0.56     16488

[[  43  139    0   29   50]
 [ 181 1894   14  190  420]
 [   2   94  405   84   49]
 [ 356  662   13 1632 1101]
 [ 694 1376   82 2023 4955]]
epoch:  31


100%|██████████| 67/67 [00:31<00:00,  2.15it/s]


Training data accuracy:  0.9714925373134329
Loss:  600.7891822156275
Test data accuracy:  0.5507035419699176


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.17      0.06       261
       dazai       0.56      0.59      0.58      2699
    fukuzawa       0.75      0.72      0.73       634
        mori       0.40      0.52      0.45      3764
     natsume       0.74      0.55      0.63      9130

    accuracy                           0.55     16488
   macro avg       0.50      0.51      0.49     16488
weighted avg       0.62      0.55      0.58     16488

[[  45  112    1   43   60]
 [ 226 1590   23  287  573]
 [   2   63  456   85   28]
 [ 367  329   20 1958 1090]
 [ 727  733  112 2527 5031]]
epoch:  32


100%|██████████| 67/67 [00:31<00:00,  2.15it/s]


Training data accuracy:  0.9723880597014926
Loss:  561.645224632729
Test data accuracy:  0.5562227074235808


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.23      0.06       261
       dazai       0.51      0.63      0.57      2699
    fukuzawa       0.73      0.79      0.76       634
        mori       0.46      0.39      0.42      3764
     natsume       0.74      0.59      0.66      9130

    accuracy                           0.56     16488
   macro avg       0.49      0.53      0.49     16488
weighted avg       0.62      0.56      0.58     16488

[[  61  125    1   24   50]
 [ 280 1712   19  147  541]
 [   3   68  498   34   31]
 [ 501  450   21 1473 1319]
 [1011  999  139 1554 5427]]
epoch:  33


100%|██████████| 67/67 [00:31<00:00,  2.13it/s]


Training data accuracy:  0.9735820895522388
Loss:  555.9512304080027
Test data accuracy:  0.5676249393498302


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.18      0.05       261
       dazai       0.53      0.58      0.55      2699
    fukuzawa       0.82      0.60      0.69       634
        mori       0.43      0.43      0.43      3764
     natsume       0.73      0.63      0.68      9130

    accuracy                           0.57     16488
   macro avg       0.51      0.48      0.48     16488
weighted avg       0.62      0.57      0.59     16488

[[  47  107    0   41   66]
 [ 284 1565   11  246  593]
 [   2   75  379  103   75]
 [ 372  382   11 1600 1399]
 [ 751  825   61 1725 5768]]
epoch:  34


100%|██████████| 67/67 [00:31<00:00,  2.16it/s]


Training data accuracy:  0.9779104477611941
Loss:  482.67275710113154
Test data accuracy:  0.5537967006307618


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.23      0.05       261
       dazai       0.56      0.55      0.56      2699
    fukuzawa       0.74      0.72      0.73       634
        mori       0.43      0.43      0.43      3764
     natsume       0.74      0.60      0.66      9130

    accuracy                           0.55     16488
   macro avg       0.50      0.51      0.49     16488
weighted avg       0.63      0.55      0.59     16488

[[  60  107    1   32   61]
 [ 351 1482   19  249  598]
 [   4   64  456   64   46]
 [ 520  332   24 1635 1253]
 [1013  655  114 1850 5498]]
epoch:  35


100%|██████████| 67/67 [00:31<00:00,  2.15it/s]


Training data accuracy:  0.9770149253731343
Loss:  502.0200416192993
Test data accuracy:  0.5510067928190199


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.04      0.19      0.06       261
       dazai       0.47      0.68      0.56      2699
    fukuzawa       0.76      0.70      0.73       634
        mori       0.42      0.41      0.41      3764
     natsume       0.74      0.57      0.65      9130

    accuracy                           0.55     16488
   macro avg       0.49      0.51      0.48     16488
weighted avg       0.61      0.55      0.57     16488

[[  50  130    1   27   53]
 [ 225 1827   16  161  470]
 [   5   80  441   83   25]
 [ 348  590   21 1536 1269]
 [ 716 1244  101 1838 5231]]
epoch:  36


100%|██████████| 67/67 [00:30<00:00,  2.16it/s]


Training data accuracy:  0.9779104477611941
Loss:  481.168706924824
Test data accuracy:  0.5270499757399321


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.23      0.06       261
       dazai       0.54      0.52      0.53      2699
    fukuzawa       0.76      0.68      0.72       634
        mori       0.39      0.49      0.43      3764
     natsume       0.73      0.54      0.62      9130

    accuracy                           0.53     16488
   macro avg       0.49      0.49      0.47     16488
weighted avg       0.61      0.53      0.56     16488

[[  59   96    0   39   67]
 [ 316 1406   16  365  596]
 [   3   71  434   88   38]
 [ 432  326   18 1861 1127]
 [ 933  710  101 2456 4930]]
epoch:  37


100%|██████████| 67/67 [00:31<00:00,  2.16it/s]


Training data accuracy:  0.9804477611940299
Loss:  440.8031096017343
Test data accuracy:  0.5397258612324114


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.14      0.05       261
       dazai       0.51      0.64      0.57      2699
    fukuzawa       0.74      0.72      0.73       634
        mori       0.40      0.50      0.45      3764
     natsume       0.74      0.52      0.61      9130

    accuracy                           0.54     16488
   macro avg       0.48      0.51      0.48     16488
weighted avg       0.61      0.54      0.56     16488

[[  37  124    1   43   56]
 [ 228 1735   17  254  465]
 [   1   83  459   72   19]
 [ 315  420   22 1893 1114]
 [ 691 1061  125 2478 4775]]
epoch:  38


100%|██████████| 67/67 [00:31<00:00,  2.16it/s]


Training data accuracy:  0.9808955223880597
Loss:  420.81241040911345
Test data accuracy:  0.5354196991751576


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.13      0.05       261
       dazai       0.48      0.63      0.55      2699
    fukuzawa       0.77      0.69      0.73       634
        mori       0.39      0.51      0.44      3764
     natsume       0.74      0.52      0.61      9130

    accuracy                           0.54     16488
   macro avg       0.48      0.50      0.48     16488
weighted avg       0.61      0.54      0.56     16488

[[  33  128    0   55   45]
 [ 184 1713   15  266  521]
 [   2   69  438   95   30]
 [ 248  500   17 1930 1069]
 [ 535 1161  101 2619 4714]]
epoch:  39


100%|██████████| 67/67 [00:31<00:00,  2.15it/s]


Training data accuracy:  0.981044776119403
Loss:  403.71760080732696
Test data accuracy:  0.5214701601164483


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.18      0.06       261
       dazai       0.55      0.54      0.54      2699
    fukuzawa       0.70      0.83      0.76       634
        mori       0.38      0.56      0.45      3764
     natsume       0.73      0.49      0.59      9130

    accuracy                           0.52     16488
   macro avg       0.48      0.52      0.48     16488
weighted avg       0.61      0.52      0.55     16488

[[  47  102    1   57   54]
 [ 264 1449   32  375  579]
 [   2    8  524   73   27]
 [ 326  332   19 2102  985]
 [ 763  752  168 2971 4476]]
epoch:  40


100%|██████████| 67/67 [00:31<00:00,  2.12it/s]


Training data accuracy:  0.9816417910447761
Loss:  399.97863133427086
Test data accuracy:  0.5436681222707423


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.14      0.05       261
       dazai       0.47      0.69      0.56      2699
    fukuzawa       0.74      0.73      0.73       634
        mori       0.41      0.45      0.43      3764
     natsume       0.75      0.54      0.62      9130

    accuracy                           0.54     16488
   macro avg       0.48      0.51      0.48     16488
weighted avg       0.61      0.54      0.56     16488

[[  37  138    1   41   44]
 [ 187 1870   16  189  437]
 [   4   51  460   73   46]
 [ 321  597   15 1688 1143]
 [ 641 1305  126 2149 4909]]
epoch:  41


100%|██████████| 67/67 [00:30<00:00,  2.17it/s]


Training data accuracy:  0.9804477611940299
Loss:  410.7315815006342
Test data accuracy:  0.5408782144590005


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.20      0.06       261
       dazai       0.51      0.63      0.56      2699
    fukuzawa       0.78      0.70      0.74       634
        mori       0.40      0.44      0.42      3764
     natsume       0.73      0.56      0.63      9130

    accuracy                           0.54     16488
   macro avg       0.49      0.50      0.48     16488
weighted avg       0.61      0.54      0.57     16488

[[  51  109    0   47   54]
 [ 247 1687   14  238  513]
 [   4   83  446   72   29]
 [ 416  399   16 1662 1271]
 [ 783 1004   99 2172 5072]]
epoch:  42


100%|██████████| 67/67 [00:30<00:00,  2.18it/s]


Training data accuracy:  0.9819402985074627
Loss:  369.8983376483869
Test data accuracy:  0.5488840368753033


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.04      0.14      0.06       261
       dazai       0.46      0.67      0.55      2699
    fukuzawa       0.76      0.70      0.73       634
        mori       0.41      0.46      0.43      3764
     natsume       0.74      0.55      0.63      9130

    accuracy                           0.55     16488
   macro avg       0.48      0.50      0.48     16488
weighted avg       0.61      0.55      0.57     16488

[[  36  127    1   36   61]
 [ 136 1797   16  182  568]
 [   1   93  442   70   28]
 [ 295  589   17 1714 1149]
 [ 548 1262  103 2156 5061]]
epoch:  43


100%|██████████| 67/67 [00:31<00:00,  2.16it/s]


Training data accuracy:  0.9816417910447761
Loss:  373.371107606196
Test data accuracy:  0.5129184861717613


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.21      0.05       261
       dazai       0.49      0.61      0.55      2699
    fukuzawa       0.77      0.73      0.75       634
        mori       0.39      0.47      0.43      3764
     natsume       0.74      0.49      0.59      9130

    accuracy                           0.51     16488
   macro avg       0.48      0.50      0.47     16488
weighted avg       0.61      0.51      0.54     16488

[[  54  111    1   43   52]
 [ 294 1654   19  242  490]
 [   4   56  463   85   26]
 [ 460  458   17 1785 1044]
 [1008 1089  103 2429 4501]]
epoch:  44


100%|██████████| 67/67 [00:31<00:00,  2.15it/s]


Training data accuracy:  0.9814925373134329
Loss:  380.7457914472311
Test data accuracy:  0.48968947113051914


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.28      0.05       261
       dazai       0.50      0.57      0.53      2699
    fukuzawa       0.75      0.71      0.73       634
        mori       0.39      0.46      0.42      3764
     natsume       0.74      0.47      0.57      9130

    accuracy                           0.49     16488
   macro avg       0.48      0.50      0.46     16488
weighted avg       0.61      0.49      0.53     16488

[[  74  102    1   41   43]
 [ 391 1550   23  265  470]
 [  11   60  450   89   24]
 [ 670  412   19 1722  941]
 [1443 1004  109 2296 4278]]
epoch:  45


100%|██████████| 67/67 [00:31<00:00,  2.16it/s]


Training data accuracy:  0.9855223880597015
Loss:  321.3606050482888
Test data accuracy:  0.5189228529839883


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.15      0.05       261
       dazai       0.47      0.60      0.53      2699
    fukuzawa       0.72      0.78      0.75       634
        mori       0.38      0.52      0.44      3764
     natsume       0.74      0.49      0.59      9130

    accuracy                           0.52     16488
   macro avg       0.47      0.51      0.47     16488
weighted avg       0.60      0.52      0.54     16488

[[  39  114    1   51   56]
 [ 230 1618   23  304  524]
 [   2   34  494   75   29]
 [ 293  533   24 1950  964]
 [ 664 1151  141 2719 4455]]
epoch:  46


100%|██████████| 67/67 [00:30<00:00,  2.16it/s]


Training data accuracy:  0.9838805970149254
Loss:  360.43951729318445
Test data accuracy:  0.5152231926249393


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.22      0.05       261
       dazai       0.49      0.59      0.53      2699
    fukuzawa       0.78      0.67      0.72       634
        mori       0.39      0.46      0.42      3764
     natsume       0.74      0.51      0.61      9130

    accuracy                           0.52     16488
   macro avg       0.48      0.49      0.47     16488
weighted avg       0.61      0.52      0.55     16488

[[  57  107    1   41   55]
 [ 362 1582   14  281  460]
 [   5   83  427   92   27]
 [ 466  437   16 1747 1098]
 [ 935 1046   91 2376 4682]]
epoch:  47


100%|██████████| 67/67 [00:31<00:00,  2.15it/s]


Training data accuracy:  0.9835820895522388
Loss:  336.5590182875408
Test data accuracy:  0.5576783114992722


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.17      0.06       261
       dazai       0.55      0.57      0.56      2699
    fukuzawa       0.77      0.71      0.74       634
        mori       0.40      0.48      0.44      3764
     natsume       0.74      0.59      0.65      9130

    accuracy                           0.56     16488
   macro avg       0.50      0.50      0.49     16488
weighted avg       0.62      0.56      0.58     16488

[[  45  117    1   43   55]
 [ 275 1529   24  298  573]
 [   4   44  449  101   36]
 [ 360  342   16 1799 1247]
 [ 667  756   91 2243 5373]]
epoch:  48


100%|██████████| 67/67 [00:31<00:00,  2.16it/s]


Training data accuracy:  0.982089552238806
Loss:  374.4193943850146
Test data accuracy:  0.5397865114022319


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.17      0.06       261
       dazai       0.47      0.63      0.54      2699
    fukuzawa       0.79      0.69      0.73       634
        mori       0.40      0.47      0.43      3764
     natsume       0.75      0.54      0.63      9130

    accuracy                           0.54     16488
   macro avg       0.49      0.50      0.48     16488
weighted avg       0.61      0.54      0.56     16488

[[  44  131    1   35   50]
 [ 205 1687   16  276  515]
 [   4   81  436   83   30]
 [ 371  506   16 1771 1100]
 [ 708 1159   86 2215 4962]]
epoch:  49


100%|██████████| 67/67 [00:30<00:00,  2.16it/s]


Training data accuracy:  0.9846268656716418
Loss:  312.3935881685542
Test data accuracy:  0.5306889859291606


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.16      0.04       261
       dazai       0.50      0.61      0.55      2699
    fukuzawa       0.81      0.63      0.71       634
        mori       0.39      0.46      0.42      3764
     natsume       0.74      0.54      0.62      9130

    accuracy                           0.53     16488
   macro avg       0.49      0.48      0.47     16488
weighted avg       0.61      0.53      0.56     16488

[[  42  111    0   46   62]
 [ 288 1633   13  255  510]
 [   2   81  401   89   61]
 [ 420  466   11 1714 1153]
 [ 887  966   71 2246 4960]]
epoch:  50


100%|██████████| 67/67 [00:31<00:00,  2.13it/s]


Training data accuracy:  0.986268656716418
Loss:  307.1296562335995
Test data accuracy:  0.5226225133430373


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.05      0.40      0.09       261
       dazai       0.49      0.61      0.54      2699
    fukuzawa       0.81      0.62      0.70       634
        mori       0.40      0.44      0.42      3764
     natsume       0.74      0.53      0.62      9130

    accuracy                           0.52     16488
   macro avg       0.50      0.52      0.47     16488
weighted avg       0.61      0.52      0.55     16488

[[ 104   64    1   38   54]
 [ 317 1652   11  218  501]
 [   8   82  391  115   38]
 [ 489  504   10 1660 1101]
 [1076 1067   72 2105 4810]]
epoch:  51


100%|██████████| 67/67 [00:31<00:00,  2.15it/s]


Training data accuracy:  0.9828358208955223
Loss:  328.0958066510128
Test data accuracy:  0.5230470645317807


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.16      0.05       261
       dazai       0.51      0.61      0.55      2699
    fukuzawa       0.78      0.74      0.76       634
        mori       0.38      0.50      0.43      3764
     natsume       0.74      0.50      0.60      9130

    accuracy                           0.52     16488
   macro avg       0.49      0.50      0.48     16488
weighted avg       0.61      0.52      0.55     16488

[[  42  116    1   50   52]
 [ 253 1648   17  314  467]
 [   8   36  471   91   28]
 [ 349  449   12 1899 1055]
 [ 815 1007  103 2641 4564]]
epoch:  52


100%|██████████| 67/67 [00:30<00:00,  2.16it/s]


Training data accuracy:  0.9846268656716418
Loss:  322.6685861900883
Test data accuracy:  0.48404900533721495


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.19      0.05       261
       dazai       0.39      0.74      0.51      2699
    fukuzawa       0.69      0.80      0.74       634
        mori       0.42      0.38      0.40      3764
     natsume       0.76      0.44      0.56      9130

    accuracy                           0.48     16488
   macro avg       0.46      0.51      0.45     16488
weighted avg       0.61      0.48      0.51     16488

[[  50  158    1   22   30]
 [ 261 1987   22  110  319]
 [   7   78  505   34   10]
 [ 497  922   30 1427  888]
 [1134 1990  178 1816 4012]]
epoch:  53


100%|██████████| 67/67 [00:31<00:00,  2.16it/s]


Training data accuracy:  0.9817910447761194
Loss:  318.00747525728946
Test data accuracy:  0.558163512857836


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.20      0.05       261
       dazai       0.51      0.65      0.57      2699
    fukuzawa       0.71      0.81      0.76       634
        mori       0.43      0.41      0.42      3764
     natsume       0.74      0.59      0.65      9130

    accuracy                           0.56     16488
   macro avg       0.49      0.53      0.49     16488
weighted avg       0.62      0.56      0.58     16488

[[  51  113    1   31   65]
 [ 249 1746   30  173  501]
 [   3   19  515   49   48]
 [ 462  480   28 1538 1256]
 [ 834 1041  150 1752 5353]]
epoch:  54


100%|██████████| 67/67 [00:31<00:00,  2.16it/s]


Training data accuracy:  0.9853731343283582
Loss:  320.29272439944714
Test data accuracy:  0.5776928675400291


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.11      0.05       261
       dazai       0.54      0.60      0.57      2699
    fukuzawa       0.68      0.82      0.75       634
        mori       0.42      0.50      0.46      3764
     natsume       0.74      0.60      0.66      9130

    accuracy                           0.58     16488
   macro avg       0.48      0.53      0.50     16488
weighted avg       0.62      0.58      0.59     16488

[[  30  117    1   45   68]
 [ 173 1631   36  303  556]
 [   3   22  519   64   26]
 [ 221  403   24 1876 1240]
 [ 468  872  178 2143 5469]]
epoch:  55


100%|██████████| 67/67 [00:31<00:00,  2.15it/s]


Training data accuracy:  0.9880597014925373
Loss:  282.3377397157428
Test data accuracy:  0.5090975254730713


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.17      0.05       261
       dazai       0.48      0.63      0.54      2699
    fukuzawa       0.73      0.77      0.75       634
        mori       0.39      0.51      0.44      3764
     natsume       0.75      0.46      0.57      9130

    accuracy                           0.51     16488
   macro avg       0.47      0.51      0.47     16488
weighted avg       0.61      0.51      0.54     16488

[[  45  120    1   44   51]
 [ 310 1698   21  258  412]
 [   6   46  490   71   21]
 [ 372  534   16 1924  918]
 [ 914 1164  142 2673 4237]]
epoch:  56


100%|██████████| 67/67 [00:31<00:00,  2.15it/s]


Training data accuracy:  0.9841791044776119
Loss:  335.65579095384817
Test data accuracy:  0.5586487142163998


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.14      0.05       261
       dazai       0.52      0.63      0.57      2699
    fukuzawa       0.78      0.66      0.72       634
        mori       0.40      0.45      0.43      3764
     natsume       0.73      0.59      0.65      9130

    accuracy                           0.56     16488
   macro avg       0.49      0.49      0.48     16488
weighted avg       0.61      0.56      0.58     16488

[[  36  116    0   44   65]
 [ 246 1702   19  223  509]
 [   2   77  418   88   49]
 [ 298  438   14 1707 1307]
 [ 546  970   82 2184 5348]]
epoch:  57


100%|██████████| 67/67 [00:31<00:00,  2.15it/s]


Training data accuracy:  0.9855223880597015
Loss:  307.1967837250115
Test data accuracy:  0.5684133915574964


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.14      0.05       261
       dazai       0.52      0.58      0.55      2699
    fukuzawa       0.76      0.68      0.72       634
        mori       0.42      0.42      0.42      3764
     natsume       0.73      0.63      0.68      9130

    accuracy                           0.57     16488
   macro avg       0.49      0.49      0.48     16488
weighted avg       0.61      0.57      0.59     16488

[[  36  110    1   39   75]
 [ 244 1576   19  250  610]
 [   7   74  430   89   34]
 [ 313  412   15 1565 1459]
 [ 598  860   98 1809 5765]]
epoch:  58


100%|██████████| 67/67 [00:31<00:00,  2.16it/s]


Training data accuracy:  0.9834328358208955
Loss:  330.4725972732301
Test data accuracy:  0.5328723920426978


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.22      0.05       261
       dazai       0.50      0.64      0.56      2699
    fukuzawa       0.74      0.78      0.76       634
        mori       0.41      0.39      0.40      3764
     natsume       0.75      0.55      0.64      9130

    accuracy                           0.53     16488
   macro avg       0.49      0.52      0.48     16488
weighted avg       0.62      0.53      0.57     16488

[[  57  119    1   32   52]
 [ 349 1728   25  220  377]
 [   8   26  492   72   36]
 [ 560  517   19 1463 1205]
 [1101 1072  127 1784 5046]]
epoch:  59


100%|██████████| 67/67 [00:31<00:00,  2.15it/s]


Training data accuracy:  0.9892537313432835
Loss:  265.8097332434959
Test data accuracy:  0.5026079573022805


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.16      0.05       261
       dazai       0.52      0.61      0.56      2699
    fukuzawa       0.78      0.63      0.69       634
        mori       0.36      0.54      0.43      3764
     natsume       0.74      0.45      0.56      9130

    accuracy                           0.50     16488
   macro avg       0.48      0.48      0.46     16488
weighted avg       0.61      0.50      0.53     16488

[[  43  117    0   53   48]
 [ 231 1656   15  359  438]
 [   5   68  398  137   26]
 [ 377  385   16 2048  938]
 [ 837  953   84 3114 4142]]
epoch:  60


100%|██████████| 67/67 [00:31<00:00,  2.15it/s]


Training data accuracy:  0.9873134328358208
Loss:  285.26532455518867
Test data accuracy:  0.5092794759825328


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.21      0.05       261
       dazai       0.46      0.63      0.54      2699
    fukuzawa       0.72      0.79      0.75       634
        mori       0.40      0.42      0.41      3764
     natsume       0.74      0.50      0.60      9130

    accuracy                           0.51     16488
   macro avg       0.47      0.51      0.47     16488
weighted avg       0.60      0.51      0.54     16488

[[  56  113    1   35   56]
 [ 288 1704   19  216  472]
 [   3   70  498   38   25]
 [ 565  549   24 1571 1055]
 [1100 1232  149 2081 4568]]
epoch:  61


100%|██████████| 67/67 [00:31<00:00,  2.15it/s]


Training data accuracy:  0.9864179104477612
Loss:  270.66801662640273
Test data accuracy:  0.5231077147016011


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.16      0.05       261
       dazai       0.50      0.64      0.56      2699
    fukuzawa       0.76      0.71      0.73       634
        mori       0.38      0.48      0.42      3764
     natsume       0.75      0.50      0.60      9130

    accuracy                           0.52     16488
   macro avg       0.48      0.50      0.47     16488
weighted avg       0.61      0.52      0.55     16488

[[  42  121    1   51   46]
 [ 237 1736   19  273  434]
 [   2   72  449   91   20]
 [ 404  483   18 1797 1062]
 [ 813 1045  107 2564 4601]]
epoch:  62


100%|██████████| 67/67 [00:31<00:00,  2.15it/s]


Training data accuracy:  0.9849253731343284
Loss:  307.4989870852004
Test data accuracy:  0.5325084910237748


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.18      0.05       261
       dazai       0.50      0.62      0.55      2699
    fukuzawa       0.75      0.71      0.73       634
        mori       0.40      0.48      0.43      3764
     natsume       0.75      0.53      0.62      9130

    accuracy                           0.53     16488
   macro avg       0.48      0.50      0.48     16488
weighted avg       0.62      0.53      0.56     16488

[[  48  114    0   43   56]
 [ 261 1682   19  277  460]
 [   2   73  452   76   31]
 [ 408  458   23 1793 1082]
 [ 835 1047  107 2336 4805]]
epoch:  63


100%|██████████| 67/67 [00:31<00:00,  2.14it/s]


Training data accuracy:  0.9868656716417911
Loss:  262.50159518168505
Test data accuracy:  0.5690198932557011


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.15      0.05       261
       dazai       0.55      0.56      0.55      2699
    fukuzawa       0.71      0.75      0.73       634
        mori       0.42      0.46      0.44      3764
     natsume       0.73      0.62      0.67      9130

    accuracy                           0.57     16488
   macro avg       0.49      0.51      0.49     16488
weighted avg       0.61      0.57      0.59     16488

[[  39  104    1   50   67]
 [ 262 1517   27  274  619]
 [   2   34  478   58   62]
 [ 275  368   20 1714 1387]
 [ 608  759  144 1985 5634]]
epoch:  64


100%|██████████| 67/67 [00:31<00:00,  2.15it/s]


Training data accuracy:  0.9867164179104477
Loss:  263.03256536556773
Test data accuracy:  0.5325691411935953


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.19      0.05       261
       dazai       0.49      0.64      0.55      2699
    fukuzawa       0.73      0.70      0.72       634
        mori       0.41      0.44      0.42      3764
     natsume       0.74      0.54      0.62      9130

    accuracy                           0.53     16488
   macro avg       0.48      0.50      0.47     16488
weighted avg       0.61      0.53      0.56     16488

[[  49  118    1   43   50]
 [ 238 1729   20  230  482]
 [  10   83  444   68   29]
 [ 432  505   22 1652 1153]
 [ 920 1120  120 2063 4907]]
epoch:  65


100%|██████████| 67/67 [00:31<00:00,  2.15it/s]


Training data accuracy:  0.9892537313432835
Loss:  236.74146726487479
Test data accuracy:  0.5211062590975255


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.20      0.05       261
       dazai       0.50      0.63      0.56      2699
    fukuzawa       0.78      0.68      0.72       634
        mori       0.39      0.46      0.42      3764
     natsume       0.75      0.51      0.61      9130

    accuracy                           0.52     16488
   macro avg       0.49      0.50      0.47     16488
weighted avg       0.62      0.52      0.55     16488

[[  52  114    0   40   55]
 [ 287 1708   18  235  451]
 [   8   72  429   98   27]
 [ 475  495   17 1735 1042]
 [1004 1060   86 2312 4668]]
epoch:  66


100%|██████████| 67/67 [00:31<00:00,  2.15it/s]


Training data accuracy:  0.9891044776119403
Loss:  268.61748239472155
Test data accuracy:  0.5513706938379428


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.06      0.38      0.10       261
       dazai       0.52      0.61      0.56      2699
    fukuzawa       0.76      0.73      0.74       634
        mori       0.41      0.42      0.42      3764
     natsume       0.74      0.58      0.65      9130

    accuracy                           0.55     16488
   macro avg       0.50      0.54      0.49     16488
weighted avg       0.62      0.55      0.58     16488

[[  98   62    1   44   56]
 [ 314 1642   18  219  506]
 [   6   68  460   65   35]
 [ 412  474   23 1592 1263]
 [ 860  925  107 1939 5299]]
epoch:  67


100%|██████████| 67/67 [00:31<00:00,  2.12it/s]


Training data accuracy:  0.9870149253731343
Loss:  255.81574625780686
Test data accuracy:  0.5360868510431829


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.15      0.05       261
       dazai       0.50      0.63      0.56      2699
    fukuzawa       0.77      0.67      0.72       634
        mori       0.39      0.48      0.43      3764
     natsume       0.74      0.53      0.62      9130

    accuracy                           0.54     16488
   macro avg       0.49      0.49      0.47     16488
weighted avg       0.61      0.54      0.56     16488

[[  38  116    1   42   64]
 [ 230 1709   16  269  475]
 [   6   85  423   97   23]
 [ 320  442   16 1805 1181]
 [ 673 1058   90 2445 4864]]
epoch:  68


100%|██████████| 67/67 [00:31<00:00,  2.15it/s]


Training data accuracy:  0.9880597014925373
Loss:  239.87224837466078
Test data accuracy:  0.5188015526443474


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.11      0.04       261
       dazai       0.50      0.58      0.54      2699
    fukuzawa       0.78      0.76      0.77       634
        mori       0.36      0.51      0.42      3764
     natsume       0.73      0.50      0.59      9130

    accuracy                           0.52     16488
   macro avg       0.48      0.49      0.47     16488
weighted avg       0.60      0.52      0.54     16488

[[  30  111    1   62   57]
 [ 257 1577   17  347  501]
 [   5   64  484   65   16]
 [ 272  451   18 1911 1112]
 [ 613  973  104 2888 4552]]
epoch:  69


100%|██████████| 67/67 [00:31<00:00,  2.15it/s]


Training data accuracy:  0.9882089552238806
Loss:  244.55520748968186
Test data accuracy:  0.5319019893255701


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.16      0.05       261
       dazai       0.47      0.65      0.54      2699
    fukuzawa       0.80      0.70      0.75       634
        mori       0.40      0.42      0.41      3764
     natsume       0.73      0.54      0.62      9130

    accuracy                           0.53     16488
   macro avg       0.49      0.50      0.47     16488
weighted avg       0.60      0.53      0.56     16488

[[  43  120    0   45   53]
 [ 245 1765   10  190  489]
 [   9   72  441   89   23]
 [ 352  584   16 1596 1216]
 [ 775 1254   82 2094 4925]]
epoch:  70


100%|██████████| 67/67 [00:31<00:00,  2.16it/s]


Training data accuracy:  0.9882089552238806
Loss:  245.25215349084885
Test data accuracy:  0.5439107229500243


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.23      0.05       261
       dazai       0.50      0.60      0.55      2699
    fukuzawa       0.78      0.73      0.75       634
        mori       0.42      0.42      0.42      3764
     natsume       0.75      0.57      0.65      9130

    accuracy                           0.54     16488
   macro avg       0.50      0.51      0.49     16488
weighted avg       0.62      0.54      0.58     16488

[[  59  112    0   36   54]
 [ 360 1623   16  227  473]
 [   8   31  462   94   39]
 [ 522  448   14 1588 1192]
 [ 962 1013  102 1817 5236]]
epoch:  71


100%|██████████| 67/67 [00:31<00:00,  2.15it/s]


Training data accuracy:  0.9891044776119403
Loss:  239.8119872501973
Test data accuracy:  0.5895196506550219


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.15      0.05       261
       dazai       0.53      0.53      0.53      2699
    fukuzawa       0.79      0.69      0.74       634
        mori       0.47      0.35      0.40      3764
     natsume       0.71      0.71      0.71      9130

    accuracy                           0.59     16488
   macro avg       0.51      0.49      0.49     16488
weighted avg       0.62      0.59      0.60     16488

[[  38  100    0   31   92]
 [ 320 1439   18  208  714]
 [   4   64  438   61   67]
 [ 309  408   16 1310 1721]
 [ 642  723   79 1191 6495]]
epoch:  72


100%|██████████| 67/67 [00:31<00:00,  2.15it/s]


Training data accuracy:  0.9865671641791045
Loss:  281.57980283288407
Test data accuracy:  0.5121300339640951


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.19      0.05       261
       dazai       0.49      0.58      0.53      2699
    fukuzawa       0.75      0.71      0.73       634
        mori       0.38      0.51      0.44      3764
     natsume       0.75      0.49      0.59      9130

    accuracy                           0.51     16488
   macro avg       0.48      0.50      0.47     16488
weighted avg       0.61      0.51      0.54     16488

[[  50  107    1   54   49]
 [ 338 1575   14  322  450]
 [   8   68  447   88   23]
 [ 403  439   23 1911  988]
 [ 887 1025  114 2643 4461]]
epoch:  73


100%|██████████| 67/67 [00:31<00:00,  2.14it/s]


Training data accuracy:  0.9880597014925373
Loss:  281.94136007646864
Test data accuracy:  0.530870936438622


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.02      0.20      0.04       261
       dazai       0.50      0.61      0.55      2699
    fukuzawa       0.74      0.77      0.75       634
        mori       0.43      0.43      0.43      3764
     natsume       0.75      0.54      0.63      9130

    accuracy                           0.53     16488
   macro avg       0.49      0.51      0.48     16488
weighted avg       0.62      0.53      0.57     16488

[[  52  117    0   44   48]
 [ 353 1646   24  238  438]
 [  11   24  487   84   28]
 [ 542  462   20 1615 1125]
 [1170 1064  131 1812 4953]]
epoch:  74


100%|██████████| 67/67 [00:31<00:00,  2.15it/s]


Training data accuracy:  0.9880597014925373
Loss:  248.53652323362934
Test data accuracy:  0.5236535662299855


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.23      0.05       261
       dazai       0.50      0.64      0.56      2699
    fukuzawa       0.74      0.75      0.74       634
        mori       0.42      0.41      0.42      3764
     natsume       0.75      0.53      0.62      9130

    accuracy                           0.52     16488
   macro avg       0.49      0.51      0.48     16488
weighted avg       0.62      0.52      0.56     16488

[[  59  113    1   28   60]
 [ 337 1717   24  190  431]
 [   5   41  475   92   21]
 [ 601  509   23 1556 1075]
 [1239 1078  121 1865 4827]]
epoch:  75


100%|██████████| 67/67 [00:31<00:00,  2.15it/s]


Training data accuracy:  0.986268656716418
Loss:  250.76318623967992
Test data accuracy:  0.5505822416302766


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.19      0.05       261
       dazai       0.52      0.58      0.55      2699
    fukuzawa       0.72      0.78      0.75       634
        mori       0.43      0.38      0.40      3764
     natsume       0.73      0.60      0.66      9130

    accuracy                           0.55     16488
   macro avg       0.48      0.51      0.48     16488
weighted avg       0.61      0.55      0.58     16488

[[  50  110    2   31   68]
 [ 316 1577   25  214  567]
 [   5   50  494   49   36]
 [ 492  416   27 1444 1385]
 [ 932  898  142 1645 5513]]
epoch:  76


100%|██████████| 67/67 [00:31<00:00,  2.15it/s]


Training data accuracy:  0.9873134328358208
Loss:  238.87329677463973
Test data accuracy:  0.5044881125667152


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.22      0.05       261
       dazai       0.54      0.56      0.55      2699
    fukuzawa       0.75      0.72      0.73       634
        mori       0.38      0.49      0.43      3764
     natsume       0.75      0.49      0.59      9130

    accuracy                           0.50     16488
   macro avg       0.49      0.50      0.47     16488
weighted avg       0.62      0.50      0.54     16488

[[  58  101    1   49   52]
 [ 406 1513   20  335  425]
 [   6   42  457   95   34]
 [ 563  353   17 1860  971]
 [1239  807  115 2539 4430]]
epoch:  77


100%|██████████| 67/67 [00:31<00:00,  2.15it/s]


Training data accuracy:  0.9891044776119403
Loss:  210.39363748667708
Test data accuracy:  0.5589519650655022


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.16      0.05       261
       dazai       0.50      0.66      0.57      2699
    fukuzawa       0.71      0.79      0.75       634
        mori       0.44      0.37      0.40      3764
     natsume       0.73      0.60      0.66      9130

    accuracy                           0.56     16488
   macro avg       0.48      0.52      0.48     16488
weighted avg       0.62      0.56      0.58     16488

[[  43  119    1   33   65]
 [ 254 1771   16  167  491]
 [   5   67  502   37   23]
 [ 396  522   36 1402 1408]
 [ 806 1090  155 1581 5498]]
epoch:  78


100%|██████████| 67/67 [00:31<00:00,  2.13it/s]


Training data accuracy:  0.9876119402985075
Loss:  246.40349766984374
Test data accuracy:  0.5438500727802038


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.14      0.05       261
       dazai       0.54      0.54      0.54      2699
    fukuzawa       0.78      0.70      0.74       634
        mori       0.38      0.45      0.41      3764
     natsume       0.72      0.59      0.65      9130

    accuracy                           0.54     16488
   macro avg       0.49      0.48      0.48     16488
weighted avg       0.60      0.54      0.57     16488

[[  37   99    0   53   72]
 [ 309 1445   13  321  611]
 [   4   53  446   91   40]
 [ 321  365   22 1688 1368]
 [ 706  735   90 2248 5351]]
epoch:  79


100%|██████████| 67/67 [00:31<00:00,  2.13it/s]


Training data accuracy:  0.9885074626865672
Loss:  230.08779123744083
Test data accuracy:  0.5656841339155749


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.13      0.05       261
       dazai       0.50      0.66      0.57      2699
    fukuzawa       0.78      0.72      0.75       634
        mori       0.41      0.40      0.41      3764
     natsume       0.73      0.61      0.66      9130

    accuracy                           0.57     16488
   macro avg       0.49      0.50      0.49     16488
weighted avg       0.61      0.57      0.58     16488

[[  34  116    1   37   73]
 [ 187 1786   14  213  499]
 [   6   55  457   79   37]
 [ 280  514   21 1519 1430]
 [ 565 1121   95 1818 5531]]
epoch:  80


100%|██████████| 67/67 [00:31<00:00,  2.15it/s]


Training data accuracy:  0.9891044776119403
Loss:  217.3281488736847
Test data accuracy:  0.5382096069868996


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.18      0.05       261
       dazai       0.52      0.62      0.56      2699
    fukuzawa       0.75      0.77      0.76       634
        mori       0.39      0.47      0.43      3764
     natsume       0.75      0.54      0.63      9130

    accuracy                           0.54     16488
   macro avg       0.49      0.51      0.49     16488
weighted avg       0.62      0.54      0.57     16488

[[  46  109    0   53   53]
 [ 280 1660   18  260  481]
 [   6   29  489   88   22]
 [ 420  450   24 1756 1114]
 [ 833  936  125 2313 4923]]
epoch:  81


100%|██████████| 67/67 [00:31<00:00,  2.14it/s]


Training data accuracy:  0.9877611940298507
Loss:  237.57223240088496
Test data accuracy:  0.5141314895681708


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.17      0.05       261
       dazai       0.47      0.67      0.55      2699
    fukuzawa       0.75      0.77      0.76       634
        mori       0.38      0.44      0.41      3764
     natsume       0.74      0.49      0.59      9130

    accuracy                           0.51     16488
   macro avg       0.47      0.51      0.47     16488
weighted avg       0.60      0.51      0.54     16488

[[  45  119    1   44   52]
 [ 253 1816   18  193  419]
 [   4   49  490   73   18]
 [ 382  642   23 1641 1076]
 [ 908 1274  121 2342 4485]]
epoch:  82


100%|██████████| 67/67 [00:31<00:00,  2.16it/s]


Training data accuracy:  0.99
Loss:  219.68564262741404
Test data accuracy:  0.5260795730228045


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.17      0.05       261
       dazai       0.45      0.64      0.53      2699
    fukuzawa       0.78      0.69      0.73       634
        mori       0.39      0.44      0.42      3764
     natsume       0.74      0.52      0.62      9130

    accuracy                           0.53     16488
   macro avg       0.48      0.49      0.47     16488
weighted avg       0.61      0.53      0.55     16488

[[  44  121    1   44   51]
 [ 267 1736   13  253  430]
 [   8   83  438   82   23]
 [ 383  550   17 1669 1145]
 [ 741 1328   96 2178 4787]]
epoch:  83


100%|██████████| 67/67 [00:31<00:00,  2.15it/s]


Training data accuracy:  0.9891044776119403
Loss:  245.17159431356444
Test data accuracy:  0.5100072780203785


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.18      0.05       261
       dazai       0.46      0.65      0.54      2699
    fukuzawa       0.76      0.71      0.74       634
        mori       0.40      0.45      0.42      3764
     natsume       0.74      0.49      0.59      9130

    accuracy                           0.51     16488
   macro avg       0.48      0.50      0.47     16488
weighted avg       0.61      0.51      0.54     16488

[[  47  121    0   38   55]
 [ 275 1747   14  205  458]
 [   3   81  453   81   16]
 [ 453  571   18 1700 1022]
 [1006 1285  110 2267 4462]]
epoch:  84


100%|██████████| 67/67 [00:31<00:00,  2.12it/s]


Training data accuracy:  0.9886567164179104
Loss:  257.54653660088354
Test data accuracy:  0.5486414361960213


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.13      0.04       261
       dazai       0.49      0.62      0.54      2699
    fukuzawa       0.79      0.76      0.78       634
        mori       0.41      0.46      0.43      3764
     natsume       0.73      0.56      0.64      9130

    accuracy                           0.55     16488
   macro avg       0.49      0.51      0.49     16488
weighted avg       0.61      0.55      0.57     16488

[[  34  110    1   44   72]
 [ 228 1661   16  251  543]
 [   5   44  483   76   26]
 [ 299  505   18 1720 1222]
 [ 723 1092   93 2074 5148]]
epoch:  85


100%|██████████| 67/67 [00:31<00:00,  2.12it/s]


Training data accuracy:  0.9870149253731343
Loss:  239.40389324243412
Test data accuracy:  0.5434255215914604


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.14      0.04       261
       dazai       0.51      0.64      0.56      2699
    fukuzawa       0.77      0.71      0.74       634
        mori       0.40      0.49      0.44      3764
     natsume       0.75      0.54      0.63      9130

    accuracy                           0.54     16488
   macro avg       0.49      0.50      0.48     16488
weighted avg       0.62      0.54      0.57     16488

[[  37  117    0   49   58]
 [ 261 1714   20  272  432]
 [   2   70  452   76   34]
 [ 354  458   19 1853 1080]
 [ 745 1021   94 2366 4904]]
epoch:  86


100%|██████████| 67/67 [00:31<00:00,  2.13it/s]


Training data accuracy:  0.9886567164179104
Loss:  218.17815822502632
Test data accuracy:  0.538391557496361


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.05      0.39      0.09       261
       dazai       0.49      0.58      0.53      2699
    fukuzawa       0.74      0.79      0.76       634
        mori       0.42      0.42      0.42      3764
     natsume       0.74      0.56      0.64      9130

    accuracy                           0.54     16488
   macro avg       0.49      0.55      0.49     16488
weighted avg       0.61      0.54      0.57     16488

[[ 101   67    0   33   60]
 [ 368 1569   22  238  502]
 [   6   38  498   58   34]
 [ 453  469   21 1581 1240]
 [ 963 1048  134 1857 5128]]
epoch:  87


100%|██████████| 67/67 [00:31<00:00,  2.14it/s]


Training data accuracy:  0.9894029850746269
Loss:  240.76347633966046
Test data accuracy:  0.5450630761766133


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.12      0.05       261
       dazai       0.51      0.58      0.54      2699
    fukuzawa       0.74      0.73      0.73       634
        mori       0.40      0.54      0.46      3764
     natsume       0.74      0.54      0.62      9130

    accuracy                           0.55     16488
   macro avg       0.48      0.50      0.48     16488
weighted avg       0.61      0.55      0.57     16488

[[  31  114    2   54   60]
 [ 245 1567   19  346  522]
 [   3   63  460   87   21]
 [ 256  351   25 2018 1114]
 [ 569  962  112 2576 4911]]
epoch:  88


100%|██████████| 67/67 [00:31<00:00,  2.13it/s]


Training data accuracy:  0.9873134328358208
Loss:  247.44642042627729
Test data accuracy:  0.5251091703056768


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.16      0.05       261
       dazai       0.51      0.60      0.55      2699
    fukuzawa       0.70      0.81      0.75       634
        mori       0.39      0.50      0.44      3764
     natsume       0.73      0.50      0.60      9130

    accuracy                           0.53     16488
   macro avg       0.47      0.52      0.48     16488
weighted avg       0.61      0.53      0.55     16488

[[  41  110    2   44   64]
 [ 293 1626   24  273  483]
 [   4   31  515   55   29]
 [ 332  434   27 1895 1076]
 [ 833 1015  163 2538 4581]]
epoch:  89


100%|██████████| 67/67 [00:31<00:00,  2.13it/s]


Training data accuracy:  0.9894029850746269
Loss:  224.24785457896385
Test data accuracy:  0.5563440077632217


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.12      0.05       261
       dazai       0.53      0.61      0.57      2699
    fukuzawa       0.75      0.77      0.76       634
        mori       0.39      0.47      0.43      3764
     natsume       0.73      0.57      0.64      9130

    accuracy                           0.56     16488
   macro avg       0.49      0.51      0.49     16488
weighted avg       0.61      0.56      0.58     16488

[[  31  118    0   49   63]
 [ 179 1657   21  237  605]
 [   5   28  491   78   32]
 [ 262  452   17 1767 1266]
 [ 540  858  130 2375 5227]]
epoch:  90


100%|██████████| 67/67 [00:31<00:00,  2.10it/s]


Training data accuracy:  0.991044776119403
Loss:  219.75787050001117
Test data accuracy:  0.5151625424551188


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.18      0.05       261
       dazai       0.43      0.70      0.53      2699
    fukuzawa       0.77      0.70      0.73       634
        mori       0.41      0.37      0.39      3764
     natsume       0.73      0.52      0.61      9130

    accuracy                           0.52     16488
   macro avg       0.47      0.49      0.46     16488
weighted avg       0.60      0.52      0.54     16488

[[  48  132    0   30   51]
 [ 238 1876   12  131  442]
 [   5   87  445   71   26]
 [ 467  692   22 1390 1193]
 [ 953 1579  102 1761 4735]]
epoch:  91


100%|██████████| 67/67 [00:31<00:00,  2.10it/s]


Training data accuracy:  0.9888059701492538
Loss:  236.96403330528557
Test data accuracy:  0.5254124211547793


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.22      0.05       261
       dazai       0.50      0.60      0.54      2699
    fukuzawa       0.79      0.68      0.73       634
        mori       0.41      0.44      0.42      3764
     natsume       0.75      0.54      0.63      9130

    accuracy                           0.53     16488
   macro avg       0.49      0.49      0.47     16488
weighted avg       0.62      0.53      0.56     16488

[[  57  111    0   35   58]
 [ 351 1618   11  238  481]
 [   6   75  429  103   21]
 [ 533  467   12 1640 1112]
 [1159  968   92 1992 4919]]
epoch:  92


100%|██████████| 67/67 [00:31<00:00,  2.11it/s]


Training data accuracy:  0.9885074626865672
Loss:  247.70984879371824
Test data accuracy:  0.5362688015526443


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.02      0.14      0.04       261
       dazai       0.47      0.63      0.54      2699
    fukuzawa       0.78      0.76      0.77       634
        mori       0.42      0.43      0.42      3764
     natsume       0.74      0.55      0.63      9130

    accuracy                           0.54     16488
   macro avg       0.49      0.50      0.48     16488
weighted avg       0.61      0.54      0.56     16488

[[  37  122    0   42   60]
 [ 274 1699   17  198  511]
 [   4   43  483   62   42]
 [ 408  583   15 1613 1145]
 [ 891 1199  107 1923 5010]]
epoch:  93


100%|██████████| 67/67 [00:31<00:00,  2.13it/s]


Training data accuracy:  0.9883582089552239
Loss:  252.26826009601584
Test data accuracy:  0.5487627365356623


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.13      0.05       261
       dazai       0.51      0.59      0.55      2699
    fukuzawa       0.77      0.77      0.77       634
        mori       0.40      0.46      0.43      3764
     natsume       0.72      0.57      0.64      9130

    accuracy                           0.55     16488
   macro avg       0.49      0.50      0.49     16488
weighted avg       0.61      0.55      0.57     16488

[[  34  118    1   48   60]
 [ 199 1589   19  313  579]
 [   4   44  490   63   33]
 [ 287  421   16 1734 1306]
 [ 653  939  114 2223 5201]]
epoch:  94


100%|██████████| 67/67 [00:31<00:00,  2.11it/s]


Training data accuracy:  0.9895522388059701
Loss:  214.752418506518
Test data accuracy:  0.5454269771955361


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.20      0.05       261
       dazai       0.49      0.62      0.55      2699
    fukuzawa       0.77      0.73      0.75       634
        mori       0.42      0.37      0.40      3764
     natsume       0.73      0.59      0.65      9130

    accuracy                           0.55     16488
   macro avg       0.49      0.50      0.48     16488
weighted avg       0.61      0.55      0.57     16488

[[  51  118    0   30   62]
 [ 264 1665   16  207  547]
 [   6   61  462   77   28]
 [ 483  475   18 1401 1387]
 [ 932 1090  103 1591 5414]]
epoch:  95


100%|██████████| 67/67 [00:31<00:00,  2.12it/s]


Training data accuracy:  0.9868656716417911
Loss:  248.24295491949263
Test data accuracy:  0.5399684619116933


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.17      0.05       261
       dazai       0.48      0.61      0.54      2699
    fukuzawa       0.75      0.79      0.77       634
        mori       0.41      0.44      0.43      3764
     natsume       0.74      0.55      0.63      9130

    accuracy                           0.54     16488
   macro avg       0.48      0.51      0.48     16488
weighted avg       0.61      0.54      0.57     16488

[[  44  118    0   37   62]
 [ 268 1656   18  257  500]
 [   6   43  502   65   18]
 [ 386  484   20 1671 1203]
 [ 838 1118  127 2017 5030]]
epoch:  96


100%|██████████| 67/67 [00:31<00:00,  2.12it/s]


Training data accuracy:  0.9880597014925373
Loss:  235.9858748781107
Test data accuracy:  0.5423338185346919


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.03      0.16      0.05       261
       dazai       0.51      0.63      0.57      2699
    fukuzawa       0.79      0.73      0.76       634
        mori       0.40      0.47      0.43      3764
     natsume       0.74      0.54      0.63      9130

    accuracy                           0.54     16488
   macro avg       0.49      0.51      0.49     16488
weighted avg       0.62      0.54      0.57     16488

[[  41  120    0   50   50]
 [ 240 1713   16  258  472]
 [   3   61  464   80   26]
 [ 352  449   16 1755 1192]
 [ 829  991   90 2251 4969]]
epoch:  97


100%|██████████| 67/67 [00:31<00:00,  2.12it/s]


Training data accuracy:  0.9871641791044776
Loss:  257.4263179799913
Test data accuracy:  0.5552523047064531


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.04      0.16      0.06       261
       dazai       0.55      0.58      0.56      2699
    fukuzawa       0.75      0.79      0.77       634
        mori       0.40      0.51      0.45      3764
     natsume       0.74      0.56      0.64      9130

    accuracy                           0.56     16488
   macro avg       0.49      0.52      0.50     16488
weighted avg       0.62      0.56      0.58     16488

[[  43  103    0   55   60]
 [ 245 1578   23  336  517]
 [   6   22  504   71   31]
 [ 281  376   16 1929 1162]
 [ 597  815  132 2485 5101]]
epoch:  98


100%|██████████| 67/67 [00:31<00:00,  2.13it/s]


Training data accuracy:  0.9876119402985075
Loss:  254.41562058541092
Test data accuracy:  0.5661693352741388


  0%|          | 0/67 [00:00<?, ?it/s]

              precision    recall  f1-score   support

   akutagawa       0.04      0.18      0.06       261
       dazai       0.52      0.62      0.56      2699
    fukuzawa       0.75      0.79      0.77       634
        mori       0.43      0.44      0.43      3764
     natsume       0.74      0.60      0.66      9130

    accuracy                           0.57     16488
   macro avg       0.49      0.53      0.50     16488
weighted avg       0.62      0.57      0.59     16488

[[  46  112    1   40   62]
 [ 231 1669   22  228  549]
 [   6   24  504   65   35]
 [ 332  447   16 1643 1326]
 [ 663  983  128 1883 5473]]
epoch:  99


100%|██████████| 67/67 [00:31<00:00,  2.13it/s]


Training data accuracy:  0.9888059701492538
Loss:  219.93552238559906
Test data accuracy:  0.5188622028141678
              precision    recall  f1-score   support

   akutagawa       0.03      0.20      0.06       261
       dazai       0.48      0.63      0.55      2699
    fukuzawa       0.77      0.65      0.70       634
        mori       0.39      0.48      0.43      3764
     natsume       0.75      0.50      0.60      9130

    accuracy                           0.52     16488
   macro avg       0.48      0.49      0.47     16488
weighted avg       0.61      0.52      0.55     16488

[[  53  114    0   41   53]
 [ 309 1689   15  272  414]
 [   4   67  412  124   27]
 [ 438  453   17 1808 1048]
 [ 836 1167   92 2442 4593]]
Test data accuracy:  0.5168607472100922
              precision    recall  f1-score   support

   akutagawa       0.03      0.20      0.05       261
       dazai       0.48      0.63      0.54      2699
    fukuzawa       0.77      0.65      0.70       634
   